-- Execute no SQL Editor do Supabase antes da primeira sincronização.
CREATE TABLE IF NOT EXISTS public.estampas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo text NOT NULL,
    variante text NOT NULL,
    preview_url text,
    storage_key text,
    original_relative_path text,
    original_filename text,
    original_extension text,
    content_hash text,
    processing_status text NOT NULL DEFAULT 'PENDING',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.estampas ADD COLUMN IF NOT EXISTS preview_url text;
ALTER TABLE public.estampas ADD COLUMN IF NOT EXISTS storage_key text;
ALTER TABLE public.estampas ADD COLUMN IF NOT EXISTS original_relative_path text;
ALTER TABLE public.estampas ADD COLUMN IF NOT EXISTS original_filename text;
ALTER TABLE public.estampas ADD COLUMN IF NOT EXISTS original_extension text;
ALTER TABLE public.estampas ADD COLUMN IF NOT EXISTS content_hash text;
ALTER TABLE public.estampas ADD COLUMN IF NOT EXISTS processing_status text NOT NULL DEFAULT 'PENDING';
ALTER TABLE public.estampas ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS estampas_codigo_variante_unique
    ON public.estampas (codigo, variante);

-- O indexador nunca deve reabrir uma análise já concluída quando os bytes da
-- imagem são os mesmos. Somente uma troca real de content_hash volta a fila.
CREATE OR REPLACE FUNCTION public.estampas_preservar_estado_ia()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.content_hash IS NOT DISTINCT FROM NEW.content_hash THEN
        NEW.processing_status := OLD.processing_status;
    ELSE
        NEW.processing_status := 'PENDING';
    END IF;
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS estampas_preservar_estado_ia_trigger ON public.estampas;
CREATE TRIGGER estampas_preservar_estado_ia_trigger
BEFORE UPDATE ON public.estampas
FOR EACH ROW EXECUTE FUNCTION public.estampas_preservar_estado_ia();
